// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oiwozzdttlaqmecxdwkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pd296emR0dGxhcW1lY3hkd2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzYxNzUsImV4cCI6MjA2OTk1MjE3NX0.OkgErOmlOrqyUFHJMjHW6BzhVtgPJ3y0RZqKaWjeit8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});